### PR TITLE
update the layout for landing pages to use require instead of require…

### PR DESCRIPTION
**Pull request by LiNk-NY**
…Namespace

Hi Lori, @lshep 
Would this change affect the landing pages? 
Best,
Marcel

### CODE REVIEW

**Comment by mtmorgan** [comment]
I don’t like this change. I think BiocManager should not be on the search path. This way it does not introduce namespace conflicts and encourages what I think is best practice of using fully resolved names for interactive use of such important functions

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
This is based on the discussion here https://community-bioc.slack.com/archives/C020U8LU59P/p1635436159004400
It would allow users to see that they have an old R installation after attaching the package. 
The other option is to have explicit version installation code `BiocManager::install(version = "3.14")` on the landing pages for each package. 

Also recently raised by https://stat.ethz.ch/pipermail/bioc-devel/2022-January/018788.html

-Marcel

**Comment by lshep** [comment]
I personally don't like either of these options.  They should get a warning of out-dated version already using BiocManager and people in courses and workshops should update their own material to reflect it.

**Comment by lshep** [comment]
After discussion with the core team on friday's meeting we decided to proceed with the change of requireNamespace to require.

**Comment by LiNk-NY** [comment]
We could also suggest the [`conflicted`](https://cran.r-project.org/web/packages/conflicted/index.html) package for namespace collisions. Or even import it in `BiocManager`..

See related: https://github.com/Bioconductor/BiocManager/issues/29

**Pull request merged**
