### PR TITLE
Added link to one more paper.

### PR DESCRIPTION
**Pull request by SunSummoner**
Bioconductor open software development for computational biology and bioinformatics. Added link to one more paper.

### CODE REVIEW

**Comment by lshep** [comment]
We will not be merging this PR. We are considering a revamp of the home page and will only be added limited content until the new design is pursued.  This paper is from 2004; and while it describes the original formation of Bioconductor we feel it does not belong in this section at this time.  Thank you for the effort.

**Comment by SunSummoner** [comment]
> We will not be merging this PR. We are considering a revamp of the home page and will only be added limited content until the new design is pursued. This paper is from 2004; and while it describes the original formation of Bioconductor we feel it does not belong in this section at this time. Thank you for the effort.

It's alright. I just started with bioconductor and found this paper useful. Thanks!

**Comment by lshep** [comment]
Thanks!   We will keep that in mind with the revamp and maybe move that to the featured literature page.

**Comment by SunSummoner** [comment]
> Thanks! We will keep that in mind with the revamp and maybe move that to the featured literature page.

That would be great. Can you let me know if you do? Thanks!

**Pull request closed without merging**
