### PR TITLE
Replace code of conduct by link to rmarkdown website

### PR DESCRIPTION
**Pull request by kevinrue**
Working branch for redirecting from bioconductor website to the R markdown multilingual code of conduct.

Please wait for @SaskiaFreytag to confirm what the new contents of the page should be.
(Anyone else welcome to feedback too!)

### CODE REVIEW

**Comment by lshep** [comment]
@kevinrue   ok.  I'll wait for another message from you here to let me know when all necessary review parties have approved.

**Comment by lshep** [comment]
@kevinrue checking in on this ?

**Comment by kevinrue** [comment]
I'll ping @SaskiaFreytag on Slack as well

**Comment by SaskiaFreytag** [comment]
Sorry I was moving house and on holiday. This is great.

**Pull request merged**
