### PR TITLE
Change Low Resolution Icon 

### LINKED ISSUE #257: New website: low res image
The image above 'Connect With the Community' is a bit jarring when viewed on a bigger screen due to the low resolution / small image
image

### PR DESCRIPTION
**Pull request by Sagaaah**
changed the low resolution image icon that present in home page - (added new svg file- fixes #257)
old
after adding new icon

### CODE REVIEW

**Review by LiNk-NY — APPROVED** [review]
LGTM. Thanks!

**Comment by mblue9** [comment]
Thanks @Sagaaah that looks great!

**Comment by mblue9** [comment]
Also, @Sagaaah, I'm curious - what software did you use to create the image?

**Comment by Sagaaah** [comment]
> Also, @Sagaaah, I'm curious - what software did you use to create the image?

I didn't use any software ,most of the software needed paid subscription to export the svg file. Hence,I downloaded a sample svg file from online . later, I made little changes in the code of the svg file .

**Comment by mblue9** [comment]
Ok great, thanks for the information.

**Pull request merged**
